#!/bin/sh
# SPDX-License-Identifier: CC-BY-SA-4.0
# Copyright 2018-2019 Peter A. Bigot

JSN=${JSN:-$(nrfjprog -i | sort | sed 1q)}
SERIES=$(echo ${1} | cut -c 1-5)
set -x
exec nrfjprog -s ${JSN} -f ${SERIES} --eraseall
